# Generated by Django 4.1 on 2022-08-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_errorlogging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="device_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
