# Generated by Django 4.1 on 2022-08-05 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=200, verbose_name="Asset name"),
                ),
                (
                    "hex_name",
                    models.CharField(max_length=200, verbose_name="Hexadecimal name"),
                ),
                (
                    "asset_desc",
                    models.CharField(max_length=200, verbose_name="Asset description"),
                ),
                (
                    "media_type",
                    models.CharField(max_length=200, verbose_name="Asset media type"),
                ),
                (
                    "ipfs_link",
                    models.CharField(max_length=200, verbose_name="Asset link"),
                ),
                (
                    "address_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.address",
                        verbose_name="Owner address",
                    ),
                ),
                (
                    "asset_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vkey",
                    models.CharField(max_length=200, verbose_name="Verification key"),
                ),
                ("skey", models.CharField(max_length=200, verbose_name="Signing key")),
                (
                    "payment_addr",
                    models.CharField(max_length=200, verbose_name="Payment address"),
                ),
                (
                    "policy_vkey",
                    models.CharField(
                        max_length=200, verbose_name="Policy verification key"
                    ),
                ),
                (
                    "policy_skey",
                    models.CharField(max_length=200, verbose_name="Policy signing key"),
                ),
                ("policy_id", models.CharField(max_length=200, verbose_name="PolicyId")),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Wallet name"
                    ),
                ),
                ("wallet_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "mnemonic",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mnemonic code"
                    ),
                ),
                ("balance", models.FloatField(default=0, verbose_name="Wallet balance")),
                (
                    "asset_no",
                    models.IntegerField(default=0, verbose_name="Number of assets"),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=200, verbose_name="TansactionId"),
                ),
                (
                    "payment_addr",
                    models.CharField(max_length=200, verbose_name="Payment address"),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                ("withdrawal", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PE", "Pending"), ("IL", "In Ledger")], max_length=10
                    ),
                ),
                (
                    "asset_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.asset",
                    ),
                ),
                (
                    "wallet_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="wallet_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
            ),
        ),
    ]
