# Generated by Django 4.1 on 2022-08-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="public_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
