# Generated by Django 4.1 on 2022-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallet_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="matx_raw_file",
            field=models.FileField(
                blank=True, null=True, upload_to="asset_files/", verbose_name="matx.raw"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="matx_sig_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="asset_files/",
                verbose_name="matx.signed",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="metadata_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="asset_files/",
                verbose_name="metadata.json",
            ),
        ),
    ]
