# Generated by Django 4.1 on 2022-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_asset_matx_raw_file_asset_matx_sig_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="policy_id",
            field=models.CharField(
                default="policy", max_length=200, verbose_name="Policy Id"
            ),
            preserve_default=False,
        ),
    ]
