# Generated by Django 4.1 on 2022-08-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_asset_policy_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="asset_owner",
        ),
    ]
