# Generated by Django 4.1 on 2022-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_remove_asset_asset_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_desc",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Asset description"
            ),
        ),
    ]
