# Generated by Django 4.1 on 2022-09-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_alter_asset_asset_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="mnemonic",
        ),
    ]
