# Generated by Django 4.1 on 2022-08-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_remove_product_product_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_price",
        ),
    ]
