# Generated by Django 4.1 on 2022-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0005_product_qrcode_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="qrcode_image",
            field=models.ImageField(upload_to="asset_qrcode/"),
        ),
    ]
